version: "3"

services:
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: perntodo
    ports:
      - "5432:5432"
  node:
    build: .
    restart: always
    command: tail -f /dev/null
    volumes:
      - .:/root/todo
    environment:
      - LC_ALL=C.UTF-8
    links:
      - db
    ports:
      - "3000:3000"
      - "5000:5000"
